### PR TITLE
added unit tests to quickgen and updated exposure time

### PR DESCRIPTION
**Pull request by rstaten**
This PR

- adds airmass unit test for quickgen
- adds exposure time unit test for quickgen
- updates how exposure time is set with specsim v0.5

Note: bright time vs. dark time unit test is not included since quickgen does not yet include a moon phase option as quickbrick does.

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks for these tests.  Travis skips the quickgen tests because of the specsim memory problem (desihub/specsim#43), but when I run them on my laptop I get failures, e.g.
```
======================================================================
ERROR: test_quickgen_airmass (desisim.test.test_quickgen.TestQuickgen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desisim/build/lib/desisim/test/test_quickgen.py", line 241, in test_quickgen_airmass
    cf0=desispec.io.readframe('cframe-r0-00000100.fits')
AttributeError: module 'desispec.io' has no attribute 'readframe'

======================================================================
ERROR: test_quickgen_exptime (desisim.test.test_quickgen.TestQuickgen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desisim/build/lib/desisim/test/test_quickgen.py", line 265, in test_quickgen_exptime
    cf0=desispec.io.readframe('cframe-r0-00000100.fits')
AttributeError: module 'desispec.io' has no attribute 'readframe'
```
Please update and confirm that they pass on your machine.

Not necessarily for Ryan but also noting:
* I'm also getting errors from test_quickbrick that are fixed in unmerged PR #166.  We should merge that PR and then merge master into this branch to fix those tests.
* the names of the MWS targeting bits changed in desitarget, thus the current desispec code works with desitarget 0.6.1 but not master.  I'll investigate whether we can work around this by just using bit names in our tests that haven't changed, or whether we do need a new tag of desitarget and require that for desisim prior to this merge.

**Comment by rstaten** [comment]
@sbailey This problem has been fixed. However when I now run these tests I get the following error:

======================================================================
FAIL: test_quickgen_airmass (__main__.TestQuickgen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_quickgen.py", line 247, in test_quickgen_airmass
    self.assertLess(np.median(cf0.ivar),np.median(cf1.ivar))
AssertionError: 2.7280001849116604e+34 not less than 2.6549968800909387e+34

----------------------------------------------------------------------

It is my understanding that increased airmass should yield smaller ivar, so it now seems that the unit test is doing what it should, but perhaps this error should be addressed.

**Comment by rstaten** [comment]
Is it possible for this PR to be merged? If not, I will make changes based on any comments or suggestions.

**Comment by rstaten** [comment]
@sbailey I have changed the flux of the cframe files by a factor of 1e17 and the ivar by a factor of 1e-34. It seems ok to simply add this factor for the flux, but it seems to be a bit of a kludge to simply add a factor in front of inverse variance. Is this acceptable?

**Comment by sbailey** [comment]
I made a small change to make it compatible with desitarget/master (they removed one of the Milky Way Survey mask bit names that we had previously been using as a placeholder).

The remaining test failure is a genuine one (good job!) — changing the airmass with quickgen doesn't actually impact the sky spectrum.  I added a question to issue #161 for converting quickgen and quickbrick to specsim v0.5 .  Let's see what @dkirkby says.  If this is fixable on the desisim side let's do that before this merge.  If it requires a bug fix on specsim, we could flag this as an expected failure test in the meantime and proceed with merging.

**Comment by rstaten** [comment]
I ran these tests using the updated specsim and no longer get any errors or failed tests.

**Comment by sbailey** [comment]
I've added a small update to quickgen to explicitly set `qsim.source.focal_xy` if needed so that the varying airmass tests work with both specsim master (which sets it already) and specsim v0.5 (which doesn't).  After the tests pass I will merge this PR.
